-- 코드를 입력하세요
# SELECT p.PRODUCT_CODE, p.PRICE * os.SALES_AMOUNT AS SALES
# FROM PRODUCT p
# INNER JOIN OFFLINE_SALE os
# ON p.PRODUCT_ID = os.PRODUCT_ID
# ORDER BY SALES DESC, p.PRODUCT_CODE ASC;

SELECT PRODUCT_CODE, SUM(SALES_AMOUNT * PRICE) AS SALES
FROM OFFLINE_SALE os
INNER JOIN PRODUCT p
ON os.PRODUCT_ID = p.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC