-- 코드를 입력하세요
SELECT b.ANIMAL_ID, b.NAME
FROM (SELECT ai.NAME, ai.ANIMAL_ID, DATEDIFF(ao.DATETIME, ai.DATETIME) as a
        FROM ANIMAL_INS ai INNER JOIN ANIMAL_OUTS ao
        ON ai.ANIMAL_ID = ao.ANIMAL_ID
        ORDER BY a DESC) b
LIMIT 0,2;
