-- 코드를 입력하세요
SELECT r.FOOD_TYPE, r.REST_ID, r.REST_NAME, r.FAVORITES
FROM
    (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE) a 
INNER JOIN REST_INFO r
ON a.FOOD_TYPE = r.FOOD_TYPE AND a.FAVORITES = r.FAVORITES
ORDER BY FOOD_TYPE DESC;