-- 코드를 작성해주세요

-- NTILE() 사용
# SELECT ID, (CASE
#                 WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY) = 1 THEN 'LOW'
#                 WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY) = 2 THEN 'MEDIUM'
#                 WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY) = 3 THEN 'HIGH'
#                 ELSE 'CRITICAL'
#             END) AS COLONY_NAME
# FROM ECOLI_DATA
# ORDER BY ID

-- CTE, PERCENTRANK() 사용
WITH A AS (
    SELECT ID,PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS SIZE_PER
    FROM ECOLI_DATA)
    
SELECT ID
        , CASE 
            WHEN SIZE_PER <= 0.25 THEN 'CRITICAL'
            WHEN SIZE_PER <= 0.50 THEN 'HIGH'
            WHEN SIZE_PER <= 0.75 THEN 'MEDIUM'
            ELSE 'LOW'
        END COLONY_NAME
FROM A
ORDER BY ID