-- 코드를 입력하세요

# SELECT NAME, DATETIME
# FROM ANIMAL_INS
# WHERE NAME NOT IN
#     (SELECT ai.NAME
#     FROM ANIMAL_INS ai INNER JOIN ANIMAL_OUTS ao
#     ON ai.ANIMAL_ID = ao.ANIMAL_ID)
# ORDER BY DATETIME ASC
# LIMIT 0,3;

SELECT NAME, DATETIME
FROM ANIMAL_INS
WHERE ANIMAL_ID NOT IN(SELECT ANIMAL_ID FROM ANIMAL_OUTS)
ORDER BY DATETIME ASC
LIMIT 0,3;