-- 코드를 입력하세요

# SELECT CAR_ID, COUNT(CAR_ID) AS CNT
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY CAR_ID
# HAVING COUNT(CAR_ID) > 5
# ORDER BY CAR_ID

# SELECT DATE_FORMAT(START_DATE,'%m') AS MONTH, CAR_ID
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY CAR_ID,DATE_FORMAT(START_DATE,'%Y-%m')
# HAVING COUNT(CAR_ID) >= 5
# ORDER BY MONTH ASC, CAR_ID DESC

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE 
    MONTH(START_DATE) BETWEEN 8 AND 10
    AND CAR_ID IN (SELECT CAR_ID 
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                    WHERE MONTH(START_DATE) BETWEEN 8 AND 10 
                    GROUP BY CAR_ID 
                    HAVING COUNT(CAR_ID) >= 5
                    )
GROUP BY CAR_ID, MONTH(START_DATE)
ORDER BY MONTH ASC, CAR_ID DESC