-- 코드를 입력하세요
SELECT c.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR c INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
ON c.CAR_ID = h.CAR_id
WHERE DATEDIFF(h.START_DATE, '2022-10-01') >= 0 AND c.CAR_TYPE = '세단'
GROUP BY c.CAR_ID
ORDER BY c.CAR_ID DESC;