-- 코드를 작성해주세요

SELECT b.DEPT_ID, b.DEPT_NAME_EN, ROUND(AVG(a.SAL), 0) AS AVG_SAL
FROM HR_EMPLOYEES a
INNER JOIN HR_DEPARTMENT b
ON a.DEPT_ID = b.DEPT_ID
WHERE a.DEPT_ID IN
    (SELECT hd.DEPT_ID
    FROM HR_DEPARTMENT hd 
    INNER JOIN HR_EMPLOYEES he
    ON hd.DEPT_ID = he.DEPT_ID
    GROUP BY hd.DEPT_ID)
GROUP BY a.DEPT_ID
ORDER BY AVG_SAL DESC

